-- Thin Neovim wrapper around the `ccm` (Contextual Commit Message) CLI
-- (https://github.com/legendu-net/ccm, see prd.md there): when a commit-message
-- file is opened empty, run `ccm --dry-run` and prefill the buffer with the
-- message it prints. All diffing, tool/API selection, and LLM calling live in
-- `ccm` itself; this script only detects the empty-buffer case, invokes `ccm`
-- (scoping it to the files a `.jjdescription` buffer's `JJ:` comments list, so
-- e.g. `jj split <file>` gets a message generated from just that file's diff),
-- and turns its exit code into a notification the user can act on. Supports
-- Jujutsu (`*.jjdescription`) and Git (`.git/COMMIT_EDITMSG`).

-- Human-readable reasons for `ccm --dry-run`'s documented exit codes (see
-- prd.md's Error Handling table). Codes 3, 12, 13, 14, 16 and 17 belong to
-- `--gen-config` or the editor/commit stage and are unreachable under
-- `--dry-run` (prd.md's "Check order", step 8), so they're omitted here.
local EXIT_MESSAGES = {
  [1] = "generic/unexpected error",
  [2] = "usage error",
  [4] = "not a git or jj repository",
  [5] = "config error in prompts.yaml/api.yaml",
  [6] = "no enabled tool/API in api.yaml",
  [7] = "diff generation failed",
  [8] = "nothing to diff",
  [9] = "API key resolution failed",
  [10] = "tool/API call failed",
  [11] = "malformed response from the API",
  [15] = "ccm generated an empty commit message",
}

-- Codes that mean "nothing to do" rather than a real failure — reported as a
-- warning instead of an error, same as the old script's skip-notifications.
local WARN_CODES = { [8] = true, [15] = true }

-- Cap a value at a length that stays readable once `report` writes it into the
-- buffer as comment lines; `ccm`'s stderr can be arbitrarily long (e.g. an
-- agent CLI's own error output). Cuts on character boundaries
-- (`strcharpart`, not `string.sub`) so a multi-byte UTF-8 character is never
-- split in half.
local function truncate(text, limit)
  limit = limit or 500
  local head = vim.fn.strcharpart(text, 0, limit)
  if head == text then return text end
  return head .. "…"
end

-- Matches `ccm`'s own "Commit message generated by <name> (<model>)" line.
-- Used both to pull it back out of captured stderr (`commit_message_source`)
-- and to keep it out of the streamed progress trail (`on_stderr` below),
-- since it's re-added explicitly as the success comment — writing it to the
-- buffer both ways would print it twice.
local SOURCE_LINE_PATTERN = "^Commit message generated by .+ %(.+%)$"

-- Pulls `ccm`'s own "Commit message generated by <name> (<model>)" progress
-- line back out of captured stderr, so the success comment can name which
-- tool/model actually produced the message instead of just crediting `ccm`
-- generically. Returns the line verbatim (already correctly worded/escaped by
-- `ccm`), or nil if it's missing (e.g. a future `ccm` reword) — callers fall
-- back to the generic comment in that case.
local function commit_message_source(stderr)
  for _, line in ipairs(vim.split(stderr or "", "\n", { trimempty = true })) do
    if line:match(SOURCE_LINE_PATTERN) then return line end
  end
  return nil
end

-- Extracts the file list from a `.jjdescription` buffer's `JJ:` comments, for
-- scoping `ccm --dry-run` to just the files a `jj split`/`jj commit -i`-style
-- partial-scope command is actually about — without this, `ccm` would default
-- to diffing the *entire* working copy (see prd.md's diff-scope resolution),
-- and the generated message could describe changes that have nothing to do
-- with what's actually being split/committed.
--
-- File lines look like `JJ:     M path/to/file`. Renames/copies embed the
-- change as `{old => new}`, optionally with a shared prefix/suffix
-- (`{dir => newdir}/file`); rewrite that segment to the destination path —
-- `ccm`'s own `--include`/`--exclude` resolution likewise only ever matches
-- against `<new>`, never `<old>`, for a rename/copy line (prd.md, "Diff scope
-- resolution").
--
-- Known limitation, left unaddressed: `ccm` has no way to scope its diff to a
-- revision other than the current working-copy change (`@`) — it always runs
-- plain `jj diff`, never `jj diff -r <rev>` (unlike the JJ:-comment-scoped
-- diff the previous version of this script built by hand). So this file list
-- is only meaningful when the description buffer is actually for `@`, which
-- covers the common `jj split`/`jj commit -i`/`jj describe` cases this
-- targets; a buffer opened for some other revision (e.g. `jj describe -r
-- <rev>`) would have `--include` restrict `@`'s diff to paths that belong to
-- a different change entirely.
local function jj_description_files(buf)
  local lines = vim.api.nvim_buf_get_lines(buf, 0, -1, false)
  local files = {}
  for _, line in ipairs(lines) do
    local file = line:match "^JJ:%s+[AMDRC]%s+(.+)$"
    if file then
      file = vim.trim((file:gsub("{.-%s*=>%s*(.-)}", "%1")))
      -- Skip empties so a blank path never reaches `ccm --include`.
      if file ~= "" then table.insert(files, file) end
    end
  end
  return files
end

-- Build a `BufReadPost`/`BufNewFile` callback that, when the message is still
-- empty, runs `ccm --dry-run` asynchronously and prepends its output.
-- `comment_prefixes` is the line prefix(es) the VCS uses for comments (`{
-- "JJ:", "JJCOPY:" }`, `{ "#" }`) — jj emits copy-related comment lines under
-- `JJCOPY:` rather than `JJ:`. The first prefix is the one this script itself
-- writes new comment lines with.
-- `extra_args`, if given, is a list of extra arguments appended to the `ccm`
-- invocation (e.g. `{ "--git" }` to force git handling for a `COMMIT_EDITMSG`
-- buffer, matching what's actually being committed even inside a colocated
-- git+jj repository), or a function `(buf) -> list|nil` to compute one from
-- the buffer's contents (e.g. `--include <files>` from a `.jjdescription`
-- buffer's `JJ:` comments).
local function make_prefill(comment_prefixes, extra_args)
  return function(args)
    local buf = args.buf
    local write_prefix = comment_prefixes[1]
    local function is_comment(line)
      for _, prefix in ipairs(comment_prefixes) do
        if vim.startswith(line, prefix) then return true end
      end
      return false
    end
    -- The message is empty when, ignoring comment lines, the first 15 lines
    -- contain no text. Comment lines are never touched.
    local function message_empty()
      local lines = vim.api.nvim_buf_get_lines(buf, 0, 15, false)
      for _, line in ipairs(lines) do
        if not is_comment(line) and vim.trim(line) ~= "" then return false end
      end
      return true
    end
    -- Notify the user and also drop the message into the buffer as VCS
    -- comment(s), so the record survives after the notification fades. Split on
    -- newlines because buffer lines must not contain them (stderr may be
    -- multi-line); the comment prefix keeps it out of the final message.
    -- `skip_notify`, when true, only writes the buffer comment: used when
    -- `msg` was already shown live via the streamed-stderr notifications
    -- below, so the user isn't shown the same text twice.
    local function report(msg, level, skip_notify)
      if not skip_notify then vim.notify(msg, level) end
      -- Only record the note while the buffer is still the empty auto-fill
      -- state, so a late failure never shifts text the user has begun typing.
      if not vim.api.nvim_buf_is_valid(buf) or not message_empty() then return end
      local comment = {}
      for _, line in ipairs(vim.split(msg, "\n", { trimempty = true })) do
        table.insert(comment, write_prefix .. " " .. line)
      end
      vim.api.nvim_buf_set_lines(buf, 0, 0, false, comment)
    end
    if not message_empty() then return end

    if vim.fn.executable "ccm" == 0 then
      report("Skipped commit message generation: ccm not found on $PATH", vim.log.levels.WARN)
      return
    end

    local resolved_extra_args = type(extra_args) == "function" and extra_args(buf) or extra_args

    local cmd = { "ccm", "--dry-run" }
    if resolved_extra_args then vim.list_extend(cmd, resolved_extra_args) end

    -- A plain notify, not `report`: this is an interim progress line, not a
    -- terminal outcome, so it must not get written into the buffer as a
    -- comment — the buffer is still in the empty state at this point, and
    -- `report` would otherwise leave it behind as a stray leftover line even
    -- on a fully successful run.
    vim.notify("Generating commit message using: " .. table.concat(cmd, " ") .. "…", vim.log.levels.INFO)

    -- ccm writes its own progress lines ("generating diff…", "calling
    -- <tool>…", etc.) to stderr as it goes, ahead of the final "Commit
    -- message generated by …" line `commit_message_source` looks for below.
    -- Diffing and the LLM call can both be slow, so surface those lines live
    -- instead of only finding out what happened once the whole (possibly
    -- long) run has already finished. They go to both `vim.notify` (for an
    -- immediate toast) and the buffer itself, appended as VCS comments below
    -- any already-appended progress line — `vim.notify` output disappears
    -- quickly and truncates long text, so the buffer copy is what gives the
    -- user something they can actually scroll back through and read in full.
    -- A custom `stderr` handler stops `vim.system` from buffering into
    -- `out.stderr` (see `:h vim.system()`), so the chunks are collected by
    -- hand into `stderr_chunks` for the exit-time parsing below.
    local stderr_chunks = {}
    local stderr_pending = ""
    local progress_line_count = 0
    -- `skip_buffer`, when true, still shows the toast but leaves the buffer
    -- alone: used for the "Commit message generated by …" line so it isn't
    -- written to the buffer twice — once here mid-trail, once more precisely
    -- (with `commit_message_source`) as the explicit success comment below.
    local function report_progress(line, skip_buffer)
      line = truncate(line)
      vim.notify(line, vim.log.levels.INFO)
      if skip_buffer then return end
      -- Only touch the buffer while it's still in the empty auto-fill state,
      -- so a user who starts typing mid-run is never interrupted.
      if not vim.api.nvim_buf_is_valid(buf) or not message_empty() then return end
      vim.api.nvim_buf_set_lines(buf, progress_line_count, progress_line_count, false, { write_prefix .. " " .. line })
      progress_line_count = progress_line_count + 1
    end
    local function on_stderr(err, data)
      -- Match the default (non-function) stderr handler's behavior (see
      -- `:h vim.system()` / `vim._system`), which raises on a pipe read error
      -- instead of silently treating it as EOF.
      if err then error(err) end
      if not data then
        local line = vim.trim(stderr_pending)
        if line ~= "" then report_progress(line, line:match(SOURCE_LINE_PATTERN) ~= nil) end
        return
      end
      -- `text = true` only normalizes line endings for stdout/stderr when using
      -- the default buffered handler; a custom handler like this one gets the
      -- raw bytes, so CRLF is normalized by hand to keep `stderr_chunks`
      -- equivalent to what `out.stderr` would have contained.
      data = data:gsub("\r\n", "\n")
      table.insert(stderr_chunks, data)
      stderr_pending = stderr_pending .. data
      local lines = vim.split(stderr_pending, "\n")
      stderr_pending = table.remove(lines)
      for _, line in ipairs(lines) do
        line = vim.trim(line)
        if line ~= "" then report_progress(line, line:match(SOURCE_LINE_PATTERN) ~= nil) end
      end
    end

    vim.system(
      cmd,
      { text = true, stderr = vim.schedule_wrap(on_stderr) },
      vim.schedule_wrap(function(out)
        -- ccm can take a moment; skip touching the buffer if the user has
        -- begun typing in the meantime.
        if not vim.api.nvim_buf_is_valid(buf) or not message_empty() then return end

        local stderr = table.concat(stderr_chunks)

        if out.code ~= 0 then
          -- Whether stderr has already been written out, both as `vim.notify`
          -- toasts and as buffer comments, line-by-line while ccm ran (see
          -- `on_stderr`/`report_progress`) — if so, `report` below should
          -- neither renotify nor re-append that same text, just point at it.
          stderr = vim.trim(stderr)
          local already_streamed = stderr ~= ""
          local detail
          if already_streamed then
            detail = "ccm (exit " .. tostring(out.code) .. "): see the comments below for the full error"
          else
            -- `EXIT_MESSAGES` is only needed as a fallback for the case
            -- stderr came back empty, so nothing was streamed to point at.
            local text = EXIT_MESSAGES[out.code] or ("unexpected exit code " .. tostring(out.code))
            detail = "ccm (exit " .. tostring(out.code) .. "): " .. text
          end
          local level = WARN_CODES[out.code] and vim.log.levels.WARN or vim.log.levels.ERROR
          report(detail, level, already_streamed)
          return
        end

        -- ccm exits 0 only with a non-blank message under --dry-run (a blank
        -- or fence/quote-wrapped-to-blank response is exit code 15), and
        -- already strips any wrapping code fence or quotes itself (see
        -- prd.md's "Response cleanup") — so stdout is used as-is here, just
        -- trimmed of the surrounding whitespace ccm's byte-exact passthrough
        -- otherwise preserves.
        local msg = vim.trim(out.stdout or "")

        local lines = vim.split(msg, "\n")
        -- Trailing empty line to separate the message from the VCS comments.
        table.insert(lines, "")
        vim.api.nvim_buf_set_lines(buf, 0, 0, false, lines)

        -- Append the source line after the progress trail `report_progress`
        -- already wrote above, instead of inserting it at the very top ahead
        -- of that trail — keeping insertion order consistent: every comment
        -- line this run adds, progress or final, ends up appended in the
        -- order it was produced.
        local source = commit_message_source(stderr) or "Commit message generated by ccm"
        local insert_at = #lines + progress_line_count
        vim.api.nvim_buf_set_lines(buf, insert_at, insert_at, false, { write_prefix .. " " .. source })
      end)
    )
  end
end

---@type LazySpec
return {
  "AstroNvim/astrocore",
  ---@type AstroCoreOpts
  opts = {
    autocmds = {
      prefill_commit_msg = {
        {
          event = { "BufReadPost", "BufNewFile" },
          pattern = "*.jjdescription",
          desc = "Prefill jj description with an AI-generated commit message via ccm",
          -- Scope ccm's diff to the JJ:-listed files, if any (e.g. a `jj
          -- split <file>`/`jj commit -i` invocation) — see
          -- jj_description_files. Falls back to ccm's own default (the whole
          -- working copy) when the buffer lists none.
          callback = make_prefill({ "JJ:", "JJCOPY:" }, function(buf)
            local files = jj_description_files(buf)
            if #files == 0 then return nil end
            local args = { "--include" }
            vim.list_extend(args, files)
            return args
          end),
        },
        {
          event = { "BufReadPost", "BufNewFile" },
          pattern = "*.git/*COMMIT_EDITMSG",
          desc = "Prefill git commit message with an AI-generated commit message via ccm",
          -- Force git handling: this buffer means a git commit is actually
          -- happening, even inside a colocated git+jj repository where ccm
          -- would otherwise default to jj.
          callback = make_prefill({ "#" }, { "--git" }),
        },
      },
    },
  },
}
